config/routes.rb
Rails.application.routes.draw do

  resources :images do
    collection do
      get :tag_cloud
      get :all
      post :create_from_url
      get :create_from_url
    end
    
    member do
      post :remove_tag
      patch :add_tag
      post :imagga
    end
  end

  root 'images#index'

end

app/models/image.rb
require 'base64'
require 'open-uri'
require 'digest'

class Image < ActiveRecord::Base
  acts_as_taggable
  anaconda_for :asset, base_key: :asset_key, host: ENV['IMAGE_HOSTNAME']
  attr_accessor :extension_for_upload

  scope :untagged, ->{ tagged_with(ActsAsTaggableOn::Tag.all.map(&:to_s), exclude: true) }
  
  def self.set_all_imagga_tags!(max_tag_count: 10)
    # Ignore things that have tags over the threshold
    Image.find_each do |image|
      next if image.tags.size > max_tag_count
      begin
        sleep(1)
        puts "Tagging: #{image.id}..."
        image.set_imagga_tags!
        print "Success! Added #{image.tags.size} tags"
      rescue => e
        print "Failed: #{e.message}"
        next
      end
    end
  end
  
  def self.update_all_hashes!
    Image.find_each do |image|
      puts "Updating hash for #{image.id}"
      begin
        image.update_hash!
      rescue Exception => ex
        puts "  Failed to update hash for #{image.id}: #{ex}"
      end
    end
  end
  
  def self.import_from_url(url)
    image = Image.create
    image.extension_for_upload = File.extname(url)
    image.import_file_to_anaconda_column(url, :asset)
    return image
  end

  def asset_key
    o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
    s = (0...24).map { o[rand(o.length)] }.join
    "assets/#{s}#{extension_for_upload}"
  end
  
  def get_imagga_tags
    image_url = asset_url
    api_key    = ENV['IMAGGA_API_KEY']
    api_secret = ENV['IMAGGA_API_SECRET']

    auth = 'Basic ' + Base64.strict_encode64( "#{api_key}:#{api_secret}" ).chomp
    response = RestClient.get "https://api.imagga.com/v1/tagging?url=#{image_url}", { :Authorization => auth }

    tags = JSON.parse( response )
  end
  
  def set_imagga_tags!
    data = get_imagga_tags
    data["results"][0]["tags"].each do |t|
      
      if t["confidence"] > 15      
        self.tag_list.add( t["tag"] )
        save
        self.taggings.order( created_at: :desc ).first.update_attributes( confidence: t["confidence"] )
      end
    end
  end
  
  def tag_list_with_confidence
  taggings.order( confidence: :desc, created_at: :desc )
  end
  
  def tag_list_by_confidence
    tag_list_with_confidence.collect{ |t| t.tag.name }
  end
  
  def update_hash!
    data = open( asset_url ).read
    digest = Digest::SHA256.hexdigest data
    self.update_attributes( digest: digest )
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  
  before_action :load_image, only: [:show, :update, :add_tag, :remove_tag, :imagga, :destroy]

  def index
    if params[:q].present?
      
      where_clause = params[:q].split( "," ).collect{ |s| "name ILIKE '%#{s.strip}%' ESCAPE '!'"}.join( " OR " )
      
      tag_ids = ActsAsTaggableOn::Tag.where( where_clause ).collect{ |t| t.id }
      
      @taggings = ActsAsTaggableOn::Tagging.includes( :taggable ).where( tag_id: tag_ids ).order( "confidence DESC, taggings.created_at DESC" ).page( params[:page] ).per( 24 )
      
      @images = @taggings.collect{ |t| t.taggable }.uniq
      
      if @images.size == 1
        redirect_to @images.first and return
      end
    else
      @images = Image.all.order("RANDOM()").first(4)
    end
  end

  def all
    @images = Image.all.order( created_at: :desc ).page( params[:page] ).per( 24 )
  end
  
  def tag_cloud
    @tags = Image.tag_counts_on(:tags)
  end

  def show
  end

  def update
    if @image.update_attributes( image_params )
      if params[:untagged] && @untagged_image = Image.untagged.last
        redirect_to image_path(@untagged_image, untagged: true)
      else
        redirect_to @image
      end
    else
      flash[:notice] = "Image failed to save."
      redirect_to @image
    end
  end
  
  def create_from_url
    @image = Image.import_from_url(params[:image_url].strip)
    @image.update_hash!
  
    @duplicate = Image.where( "digest = ? AND id != ?", @image.digest, @image.id ).first
  
    if @duplicate.present?
      flash[:notice] = "Image was a duplicate."
      
      @image.destroy
      
      redirect_to @duplicate
    else
      redirect_to image_path(@image)
    end
  end

  def create
    @image = Image.new( image_params )
    
    if @image.save
      @image.update_hash!
    
      @duplicate = Image.where( "digest = ? AND id != ?", @image.digest, @image.id ).first
    
      if @duplicate.present?
        flash[:notice] = "Image was a duplicate."
        
        @image.destroy
        
        redirect_to @duplicate
      else
        redirect_to image_path(@image, untagged: true)
      end
    else
      flash[:notice] = "Image failed to save."
      redirect_to images_path
    end
  end
  
  def destroy
    @image.destroy

    flash[:notice] = "Destroyed."
    redirect_to images_path
  end
  
  def add_tag
    @image.tag_list.add(params[:image][:tag].split(","))
    @image.save
    redirect_to @image
  end

  def remove_tag
    @image.tag_list.remove(params[:tag])
    @image.save
    redirect_to @image
  end
  
  def imagga
    @image.set_imagga_tags!
    redirect_to @image
  end

  private

  def image_params
    params.require(:image).permit(
            :name,
            :tag_list,
            Image.anaconda_fields_for( :asset )
            )
  end
  
  def load_image
    @image = Image.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def paginate objects, options = {}
    options.reverse_merge!( theme: 'twitter-bootstrap-3' )

    super( objects, options )
  end

end

app/helpers/images_helper.rb
module ImagesHelper
  include ActsAsTaggableOn::TagsHelper
  
  def tag_label(tag: tag, show_remove: false)
    content_tag(:span, class: "label #{label_class_for_tag(tag)}") do
      output = [content_tag(:span, tag.tag.name, title: "Confidence: #{tag.confidence}")]
      output << link_to("<i class='fa fa-times'></i>".html_safe, remove_tag_image_path(tag: tag.tag.name), method: :post) if show_remove
      output.join(" ").html_safe
    end
    
  end
  
  def label_class_for_tag(tag)
    if tag.confidence >= 100
      'label-success'
    elsif tag.confidence >= 50
      'label-primary'
    elsif tag.confidence >= 30
      'label-info'
    elsif tag.confidence >= 20
      'label-warning'
    elsif tag.confidence >= 10
      'label-danger'
    else
      'label-default'
    end
  end
end

app/views/images/all.html.haml
.row
  .col-lg-12
    .images-grid
      - @images.each_slice(4) do |images|
        .row
          - images.each do |image|
            .col-md-3
              .well
                %a{ href: image_path( image, untagged: params[:untagged] ) }
                  %img.img.img-responsive.center-block{ src: image.asset_url }
      :javascript
        $( document ).ready( function(){
          $( '.images-grid img' ).each( function( el ){
            $( el ).css( '-webkit-animation-play-state', 'paused' );
          });
        })
    - if @images.respond_to?(:total_count)
      .text-center
        = paginate @images

app/views/images/index.html.haml
.row
  .col-lg-12
    .images-grid
      - @images.each_slice(4) do |images|
        .row
          - images.each do |image|
            .col-md-3
              .well
                %a{ href: image_path( image, untagged: params[:untagged] ) }
                  %img.img.img-responsive.center-block{ src: image.asset_url }
      :javascript
        $( document ).ready( function(){
          $( '.images-grid img' ).each( function( el ){
            $( el ).css( '-webkit-animation-play-state', 'paused' );
          });
        })
    - if @taggings.respond_to?(:total_count)
      .text-center
        = paginate @taggings

- unless params[:q].present?
  .row
    .col-md-12.text-center
      %h2
        You Have #{Image.count} Amazing Gifs

:coffeescript
  $( document ).ready ->
    $("input#q").focus()

app/views/images/show.html.haml
.row
  .col-md-3
    .well
      = simple_form_for @image, url: add_tag_image_path(@image), html: { class: 'form-inline' } do |f|
        = f.input :tag, input_html: {value: nil}, placeholder: "Tag", label: false
        = f.submit "Add Tag", class: 'btn btn-primary'
      
      :coffeescript
        availableTags = #{ActsAsTaggableOn::Tag.all.map(&:to_s).to_json}
        
        $( "#image_tag").autocomplete({
          minLength: 0,
          source: availableTags
        })
      %hr
      = link_to "Auto tag with Imagga", imagga_image_path( @image ), method: :post, class: 'btn btn-sm btn-default'
    
    %ul.tags
      - @image.tag_list_with_confidence.each do |tag|
        %li= tag_label(tag: tag, show_remove: true)

  .col-md-9
    .row
      .col-md-2
        - prev_image = Image.where("id < ?", @image.id).order(id: :desc).first
        - if prev_image
          = link_to "<i class='fa fa-arrow-left'></i>".html_safe, image_path(prev_image), { id: "prev_image" }
      .col-md-8
        = @image.name
      .col-md-2.text-right
        - next_image = Image.where("id > ?", @image.id).order(id: :asc).first
        - if next_image
          = link_to "<i class='fa fa-arrow-right'></i>".html_safe, image_path( next_image ), { id: "next_image" }

    %img.center-block{style: "max-width: 100%; max-height: 80%;", src: @image.asset_url }
    
    .text-right
      = link_to "Destroy", image_path( @image ), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" }

    - if params[:untagged].present?
      :javascript
        $( "#image_tag_list" ).focus();

    :javascript
      $( document ).ready( function(){
        
        $(document).bind('keyup', 'ctrl+t', function(){
          $( "#image_tag_list" ).focus();
        });


        // e.g. replace '$' sign with 'EUR'
        $(document).bind('keyup', 'ctrl+n', function(){
          window.location.href = "/images/#{@image.id + 1}";
        });

        // e.g. replace '$' sign with 'EUR'
        $(document).bind('keyup', 'ctrl+p', function(){
          window.location.href = "/images/#{@image.id - 1}";
        });


      });

app/views/images/tag_cloud.html.haml
- tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class|
  = link_to tag.name, "/images?q=#{tag.name}", :class => css_class

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %title=content_for?(:page_title) ? "#{content_for(:page_title)} — Gif Manager" : "Gif Manager"

    = stylesheet_link_tag    "application", :media => "all", data: { turbolinks_track: true }
    = javascript_include_tag "application", data: { turbolinks_track: true }

    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/

    = csrf_meta_tags

    :javascript
      Turbolinks.enableTransitionCache();
    %link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css", :rel => "stylesheet"}/
  %body.body{ class: content_for?(:body_class) ? content_for(:body_class) : "" }

    %nav.navbar.navbar-default
      .container-fluid
        %ul.nav.navbar-nav
          %li= link_to "Home", root_path
          - @untagged_image = Image.untagged.last
          - if @untagged_image.present?
            %li= link_to "Untagged Queue", image_path(@untagged_image, untagged: true)
          
          %li= link_to "All Tags", tag_cloud_images_path
          %li= link_to "All Images", all_images_path
          
        .navbar-form.navbar-right
          = simple_form_for Image.new, html: { class: 'form-horizontal' } do |f|
            .text-center
              = f.anaconda :asset, auto_upload: true, auto_submit: true

        .navbar-form.navbar-right
          = form_tag create_from_url_images_path, method: :post, class: "form-inline" do
            .form-group
              = text_field_tag 'image_url', nil, class: "form-control", placeholder: "http://"
              = submit_tag "Add From URL", class: "btn btn-default"

        .navbar-form.navbar-right
          = form_tag '/', method: :get, class: "form-inline" do
            .form-group
              = text_field_tag 'q', params[:q], class: "form-control", placeholder: "Search"
              = submit_tag "Search", class: "btn btn-primary"

    .container-fluid
      .row
        .col-lg-12.col-md-12
          - if flash[:notice].present?
            .alert.alert-warning
              = flash[:notice]
        
          = yield